apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-prediction-app
  labels:
    app: salary-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salary-predictor
  template:
    metadata:
      labels:
        app: salary-predictor
    spec:
      containers:
      - name: salary-predictor
        image: salary-prediction-app:latest # Replace with your registry image
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
