name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-validate:

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install "dvc[s3]"

      - name: Pull Data and Model from S3
        run: |
          dvc pull --force

      - name: Verify Project Structure
        run: |
          ls
          ls src
          ls streamlit_app
          ls models

      - name: Build Docker Image
        run: |
          docker build -t employee-salary-app .

      - name: Validate Docker Build
        run: |
          docker images